### ISSUE TITLE
Generate CRL

### ISSUE THREAD

**Issue by joepeding** [nuts-foundation/nuts-development-network-ca#4]
Depending on your configuration, you might need a CRL for the Nuts network CA in order for certificates to be accepted. 
In my experience nginx complains when loading a concatenated CRL that does not contain a CRL for the Nuts network CA.

I solved this by generating an empty CRL. Figuring out how takes time, so it might be useful for others to add the empty CRL to the repo as well. Below is how I solved it. I'll hopefully turn this into a PR soonish.

---

Start by generating a config file:
```
# Unnamed section of generic options

# Section for default ca option
[ca]
default_ca = nuts

[nuts]
database = ./database.txt
certificate = ./ca.pem
private_key = ./ca.key
default_md = default
default_crl_days = 3000
```
And then:
```
openssl ca -gencrl -config nuts.conf -out nuts.crl
```

**Comment by reinkrul** [comment]
Thanks for the suggestion, I included the generator step in the script: https://github.com/nuts-foundation/nuts-development-network-ca/pull/5

Edit: I just read that you were intending to open a PR with this change. Sorry, I was too eager :-)

**Comment by joepeding** [comment]
Great, thanks!
